version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1
  python: circleci/python@1.5.0
  

jobs:
  job1:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install jq
          command: |
            echo "Hello world"
      

           
workflows:
  version: 2
  Infra-Setup-1:
    jobs:
      - job1
      
